/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppForm`; params?: Router.UnknownInputParams; } | { pathname: `/AppItem`; params?: Router.UnknownInputParams; } | { pathname: `/AppList`; params?: Router.UnknownInputParams; } | { pathname: `/AppTab`; params?: Router.UnknownInputParams; } | { pathname: `/Database`; params?: Router.UnknownInputParams; } | { pathname: `/navigation.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AppForm`; params?: Router.UnknownOutputParams; } | { pathname: `/AppItem`; params?: Router.UnknownOutputParams; } | { pathname: `/AppList`; params?: Router.UnknownOutputParams; } | { pathname: `/AppTab`; params?: Router.UnknownOutputParams; } | { pathname: `/Database`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation.d`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/AppForm${`?${string}` | `#${string}` | ''}` | `/AppItem${`?${string}` | `#${string}` | ''}` | `/AppList${`?${string}` | `#${string}` | ''}` | `/AppTab${`?${string}` | `#${string}` | ''}` | `/Database${`?${string}` | `#${string}` | ''}` | `/navigation.d${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AppForm`; params?: Router.UnknownInputParams; } | { pathname: `/AppItem`; params?: Router.UnknownInputParams; } | { pathname: `/AppList`; params?: Router.UnknownInputParams; } | { pathname: `/AppTab`; params?: Router.UnknownInputParams; } | { pathname: `/Database`; params?: Router.UnknownInputParams; } | { pathname: `/navigation.d`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
